# Generated by Django 2.2 on 2019-05-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
